services:
  mysql:
    image: mysql:8.0
    container_name: mysql_demobase
    environment:
      MYSQL_DATABASE: demobase
      MYSQL_USER: demobase_user
      MYSQL_PASSWORD: demobase_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ahorcado-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-udemobase_user", "-pdemobase_pass"]
      interval: 10s
      timeout: 5s
      retries: 5

  ahorcado-app:
    build: .
    container_name: ahorcado-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/demobase?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: demobase_user
      SPRING_DATASOURCE_PASSWORD: demobase_pass
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ahorcado-net

volumes:
  mysql_data:

networks:
  ahorcado-net:
